package com.rongrong.plan;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.animation.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 int primary=Color.rgb(255,143,179); LinearLayout list; ProgressBar progress; TextView pct,fortune,animal; ArrayList<Task> tasks=new ArrayList<>(); String[] animals={"🐰垂耳兔","🐱橘猫","🐶柯基","🐼小熊猫","🐹仓鼠","🐧企鹅"}; Random r=new Random();
 public void onCreate(Bundle b){super.onCreate(b); seed(); build(); new Handler().postDelayed(()->encourage(),500);} 
 void seed(){tasks.add(new Task("教资科一：刷题 40 道",40,3));tasks.add(new Task("英语六级：听力精听 30 分钟",30,2));tasks.add(new Task("Python：完成 1 个函数练习",45,2));tasks.add(new Task("AIGC 工作流：复盘笔记",20,1));}
 void build(){ScrollView sv=new ScrollView(this); LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,36,28,28);GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0xfffff2f7,0xffeff9ff,0xfff5fff1});root.setBackground(bg);sv.addView(root);setContentView(sv);
  TextView title=txt("绒绒计划局",34,true);root.addView(title);root.addView(txt("躺平式做计划，毛茸茸陪你通关",16,false)); animal=txt(animals[r.nextInt(animals.length)]+" 今日陪学中",22,true);root.addView(card(animal));
  LinearLayout colors=new LinearLayout(this); colors.setPadding(0,16,0,8); int[] cs={0xffff8fb3,0xff58b8ff,0xff62d487,0xffb89cff}; for(int c:cs){Button b=btn(" ");b.setBackground(round(c,60));b.setOnClickListener(v->{primary=c; refreshColors(root);});colors.addView(b,new LinearLayout.LayoutParams(80,80));} root.addView(colors);
  TextView q=txt("AI 懒人计划生成",22,true);root.addView(q); EditText input=new EditText(this);input.setHint("输入：任务名 + 周期 + 目标量，例如 30天六级单词1500个");input.setSingleLine(false);input.setBackground(round(0xffffffff,34));input.setPadding(24,12,24,12);root.addView(input);
  Button gen=btn("一键生成并导入日历打卡");root.addView(gen); gen.setOnClickListener(v->{String s=input.getText().toString().trim(); if(s.length()==0)s="30天六级单词1500个"; tasks.add(new Task("AI计划："+s+"（今日拆分项）",35,3)); addTask(tasks.get(tasks.size()-1)); update(); toast("已生成每日拆分计划，可在今日清单打卡");});
  root.addView(txt("今日进度",22,true)); progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setProgressDrawable(round(primary,24));root.addView(progress,new LinearLayout.LayoutParams(-1,38)); pct=txt("0%",18,true);root.addView(pct);
  root.addView(txt("日视图 · 今日任务清单",22,true)); list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list); for(Task t:tasks)addTask(t);
  LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);root.addView(actions); String[] bs={"🔮 每日星座求签","⏱ 开启番茄专注 25:00","🌧 白噪音：雨声/咖啡馆/森林","🛌 一键休息日","📊 数据复盘与成就勋章"}; for(String s:bs){Button b=btn(s);actions.addView(b); b.setOnClickListener(v->feature(((Button)v).getText().toString()));} }
 void addTask(Task t){CheckBox cb=new CheckBox(this);cb.setText(t.name+" · "+t.minutes+"分钟 · 权重"+t.weight);cb.setTextSize(17);cb.setPadding(18,14,18,14);cb.setBackground(round(0xffffffff,34));cb.setButtonTintList(android.content.res.ColorStateList.valueOf(primary));cb.setOnCheckedChangeListener((v,c)->{t.done=c; pop(v); update();});list.addView(cb,new LinearLayout.LayoutParams(-1,-2));}
 void update(){int total=0,done=0;for(Task t:tasks){total+=t.weight;if(t.done)done+=t.weight;}int p=total==0?0:done*100/total;progress.setProgress(p);pct.setText(p+"% · 按任务权重实时计算");}
 void encourage(){new AlertDialog.Builder(this).setTitle("毛茸茸给你打气").setMessage(animals[r.nextInt(animals.length)]+" 举牌：今天也不用硬撑，完成一小步就超棒！").setPositiveButton("收下鼓励",null).show();}
 void feature(String s){ if(s.contains("求签")){fortune=txt("学业运★★★★★\n心情值：软乎乎上升\n今日小贴士：先做高权重任务，绒绒会给你撒花～",18,false); new AlertDialog.Builder(this).setTitle("专属动物签文卡片").setView(fortune).setPositiveButton("保存到历史",null).show();} else toast(s+" 已准备好（演示版入口）");}
 TextView txt(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(0xff49313b);v.setPadding(4,10,4,10);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(round(primary,42));return b;} Drawable round(int c,int rad){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(rad);g.setStroke(2,0x22ffffff);return g;} View card(View v){v.setBackground(round(0xffffffff,40));v.setPadding(24,24,24,24);return v;} void pop(View v){v.animate().scaleX(.92f).scaleY(.92f).setDuration(90).withEndAction(()->v.animate().scaleX(1).scaleY(1).setDuration(160).start()).start();animal.setText(animals[r.nextInt(animals.length)]+( ((CheckBox)v).isChecked()?" 蹦跳撒花 ✨":" 歪头等你回来～"));} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} void refreshColors(View root){getWindow().setNavigationBarColor(primary); toast("主色已同步到按钮、进度条、导航栏"); build();}
 static class Task{String name;int minutes,weight;boolean done;Task(String n,int m,int w){name=n;minutes=m;weight=w;}}
}
